---
name: bosh_demo

director_uuid: b957be6f-42b8-4182-9fa7-556489e8cf88

releases:
- {name: bosh_feature_demo, version: latest}

update:
  canaries: 0
  max_in_flight: 100
  canary_watch_time: 1000 - 30000
  update_watch_time: 1000 - 30000

instance_groups:
- name: client
  instances: 1
  jobs:
  - name: client
  azs: [z1]
  vm_type: large
  stemcell: default
  networks:
  - name: public-bosh
    default: [dns, gateway]

- name: service
  instances: 1
  jobs:
  - name: service
  azs: [z1]
  vm_type: large
  stemcell: default
  networks:
  - name: public-bosh
    default: [dns, gateway]

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: latest
